host: "127.0.0.1"
release: false
finnhub_api_key: ""

http_server:
  port: 2000
  request_timeout: 60

web_client:
  domain: "localhost"
  port: 5000

postgres:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  port: 5432
  db: "wealth_warden"

jwt:
  web_client_access: "18yslKe4&n56"
  web_client_refresh: "A2tbBCR!X4w3"
  web_client_encode_id: "k3K6E*)Dz'55WLPPk*47c0||o`20y<p/"

cors:
  allowedOrigins:
    - "http://localhost:5000"
    - "http://app:5000"
  wildcardSuffixes: []
  allowedSchemes: ["http"]

mailer:
  host: "smtp.email.com"
  port: 587
  username: "email@email.com"
  password: "aaaa bbbb cccc dddd"

seed:
  super_admin_email: "support@wealth.warden"
  super_admin_password: "password"
  member_user_email: ""
  member_user_password: ""
