{{- if and .Values.api.enabled .Values.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wealth-warden.api.name" . }}
  labels:
    {{- include "wealth-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wealth-warden.api.name" . }}
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

---
{{- if and .Values.webui.enabled .Values.webui.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wealth-warden.webui.name" . }}
  labels:
    {{- include "wealth-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wealth-warden.webui.name" . }}
  minReplicas: {{ .Values.webui.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webui.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.webui.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.webui.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.webui.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.webui.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

