{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wealth-warden.secretName" . }}
  labels:
    {{- include "wealth-warden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.postgresPassword }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtWebClientAccess }}
  jwt-web-client-access: {{ .Values.secrets.jwtWebClientAccess | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtWebClientRefresh }}
  jwt-web-client-refresh: {{ .Values.secrets.jwtWebClientRefresh | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtWebClientEncodeId }}
  jwt-web-client-encode-id: {{ .Values.secrets.jwtWebClientEncodeId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.mailerPassword }}
  mailer-password: {{ .Values.secrets.mailerPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.superAdminPassword }}
  super-admin-password: {{ .Values.secrets.superAdminPassword | b64enc }}
  {{- end }}
{{- end }}


