apiVersion: v1
kind: Service
metadata:
  name: {{ include "wealth-warden.api.serviceName" . }}
  labels:
    {{- include "wealth-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wealth-warden.api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wealth-warden.webui.serviceName" . }}
  labels:
    {{- include "wealth-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: {{ .Values.webui.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "wealth-warden.webui.selectorLabels" . | nindent 4 }}

