services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wealth_warden}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-wealth_warden}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wealth-warden

  app:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    #command: ["http"]
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "2000:2000"
    volumes:
      - ../../logs:/app/logs
      - ../../pkg/config/override:/app/pkg/config/override:ro
    networks:
      - wealth-warden

volumes:
  db:

networks:
  wealth-warden: