services:
  client:
    build:
      context: ../../
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ../../.env:/app/.env
    networks:
      - wealth-warden

networks:
  wealth-warden:
    # external: true
