services:
  client:
    build:
      context: ../../
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ../../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../.env:/app/.env
    networks:
      - wealth-warden

networks:
  wealth-warden:
    external: true
