services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Redirect HTTP â†’ HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # ACME
      - --certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL-support@wealth.warden}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - wealth-warden

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wealth_warden}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-wealth_warden}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wealth-warden

  migrate:
    profiles: ["migrate"]
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-wealth_warden}
      - POSTGRES_PORT=5432
    entrypoint: ["server"]
    command: ["migrate", "fresh-seed-basic" ]        # default args
    networks:
      - wealth-warden

  server:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-wealth_warden}
      - POSTGRES_PORT=5432
    volumes:
      - ../../logs:/app/logs
      - ../../pkg/config/override:/app/pkg/config/override:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=2000
    networks:
      - wealth-warden

  client:
    build:
      context: ../../
      dockerfile: ./build/Dockerfile.client
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`${HOST:-localhost}`) && PathPrefix(`/`)
      - traefik.http.routers.client.entrypoints=websecure
      - traefik.http.routers.client.tls.certresolver=le
      - traefik.http.services.client.loadbalancer.server.port=80
    networks:
      - wealth-warden

volumes:
  db:
  traefik_letsencrypt:

networks:
  wealth-warden: