api:
  version: "1"

host: "0.0.0.0"
release: false

http_server:
  port: 2000
  request_timeout: 60

web_client:
  domain: "localhost"
  port: 5000

postgres:
  host: "db"
  user: "postgres"
  password: "postgres"
  port: 5432
  db: "wealth_warden"

jwt:
  web_client_access: "O7yslMel&nR6"
  web_client_refresh: "M2tb,_R!X4w~"
  web_client_encode_id: "Rjy6E*)Dz'UwWLPPk*47c0||o`-Oy<p/"

cors:
  allowedOrigins:
    - "http://localhost:5000"
    - "http://app:5000"
    - "http://127.0.0.1:5000"
  wildcardSuffixes: []
  allowedSchemes: ["http"]

mailer:
  host: "smtp.x.y"
  port: 587
  username: "example@email.com"
  password: "aaaa bbbb cccc dddd"

seed:
  super_admin_email: "admin@email.com"
  super_admin_password: "password"
  member_user_email: "member@admin.com"
  member_user_password: "password"
