host: "127.0.0.1"
release: false

http_server:
  port: 2000

web_client:
  domain: "localhost"

postgres:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  port: 5432
  db: "wealth_warden"

jwt:
  web_client_access: "..."
  web_client_refresh: "..."
  web_client_encode_id: "..."

cors:
  allowedOrigins:
    - "http://localhost:3000"
    - "http://app:3000"
    - "http://127.0.0.1:3000"
  wildcardSuffixes: []
  allowedSchemes: ["http"]

seed:
  super_admin_email: "support@wealth.warden"
  super_admin_password: "password"
  member_user_email: "member@wealth.warden"
  member_user_password: "password"
