api:
  version: "1"

host: "127.0.0.1"
release: false

http_server:
  port: 2000

web_client:
  domain: "localhost"
  port: 5000

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: wealth_warden_test

jwt:
  web_client_access: "O7yslMel&nR6"
  web_client_refresh: "M2tb,_R!X4w~"
  web_client_encode_id: "Rjy6E*)Dz'UwWLPPk*47c0||o`-Oy<p/"

cors:
  allowedOrigins:
    - "http://localhost:5000"
    - "http://app:5000"
    - "http://127.0.0.1:5000"
    - "http://192.168.50.186:5000"
  wildcardSuffixes: []
  allowedSchemes: ["http"]

mailer:
  host: "smtp.x.y"
  port: 587
  username: "example@email.com"
  password: "aaaa bbbb cccc dddd"

seed:
  super_admin_email: "test_sa@wealth.warden"
  super_admin_password: "password"
  member_user_email: "test_member@wealth.warden"
  member_user_password: "password"
