services:
  client:
    build:
      context: ../../
      dockerfile: ./build/Dockerfile
      args:
        - API_BASE_URL=localhost:2000/api/v1
        - PRODUCTION_MODE=false
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - wealth-warden

networks:
  wealth-warden:
    # external: true
